version: '3.8'

services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - document_platform
    environment:
      PORT: ${PORT}
      VERSION: ${VERSION}
      FULL_URL_MYSQL: ${FULL_URL_MYSQL}
      SECRET: ${SECRET}
      LIVE_TIME_JWT: ${LIVE_TIME_JWT}

  db:
    container_name: databse
    networks:
      - document_platform
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306'

networks:
  document_platform:
